---
title: "Week-06-HPC"
author: "Matteo"
date: "2025-02-11"
output: html_document
---

https://github.com/MatteoIBiol432/Week-06-HPC

```{r}
library(doParallel)
library(parallel)
library(foreach)
```

```{r}
num_cores <- detectCores()
print(num_cores)
```
16 Cores

```{r}
start_time <- Sys.time()

for(i in 1:4000) {
  sample_data <- rnorm(100000, mean = 10, sd = 3)
  mean_val <- mean(sample_data)
}

end_time <- Sys.time()
time_taken <- end_time - start_time
print(time_taken)
```

```{r}
theoretical_time <- time_taken / (num_cores-1)
print(theoretical_time)
```

```{r}
Cores <- parallel::makeCluster(num_cores - 1)
doParallel::registerDoParallel(Cores)

start_time_parallel <- Sys.time()

foreach(i = 1:4000, .combine = c) %dopar% {
  sample_data <- rnorm(100000, mean = 10, sd = 3)
  mean_val <- mean(sample_data)
}

end_time_parallel <- Sys.time()
time_taken_parallel <- end_time_parallel - start_time_parallel
print(time_taken_parallel)

parallel::stopCluster(Cores)
```

```{r}
print(paste("Linear: ", time_taken, "Seconds"))
print(paste("Parallel Theoretical: ", theoretical_time, "Seconds"))
print(paste("Parallel: ", time_taken_parallel, "Seconds"))
```

```{r}
speedup_parallel <- as.numeric(time_taken)/ as.numeric(time_taken_parallel)
speedup_parallel_percentage <- (speedup_parallel - 1) * 100

print(paste("The program was", round(speedup_parallel_percentage, 2), "% faster using parallel processing compared to serial processing."))
```

